// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnAorSA7HRDUmn5cgd84kOfCPr_sTiuHg',
    appId: '1:428557007573:web:648f4c20d9acb501fec05c',
    messagingSenderId: '428557007573',
    projectId: 'hoodjunction-a7605',
    authDomain: 'hoodjunction-a7605.firebaseapp.com',
    storageBucket: 'hoodjunction-a7605.firebasestorage.app',
    measurementId: 'G-L7Q9B0RGMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiSsR40swmXQmVHrapND6-FfzPYH6FDJg',
    appId: '1:428557007573:android:a84f02d87afbdf40fec05c',
    messagingSenderId: '428557007573',
    projectId: 'hoodjunction-a7605',
    storageBucket: 'hoodjunction-a7605.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh5gNRLimTqFzIwgQacU2Oh7wOj0RU2ZU',
    appId: '1:428557007573:ios:3beb1a18ea47f24efec05c',
    messagingSenderId: '428557007573',
    projectId: 'hoodjunction-a7605',
    storageBucket: 'hoodjunction-a7605.firebasestorage.app',
    iosClientId: '428557007573-49riei18ab978u1phttf4le57c1p0l7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.hoodhiveFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh5gNRLimTqFzIwgQacU2Oh7wOj0RU2ZU',
    appId: '1:428557007573:ios:3beb1a18ea47f24efec05c',
    messagingSenderId: '428557007573',
    projectId: 'hoodjunction-a7605',
    storageBucket: 'hoodjunction-a7605.firebasestorage.app',
    iosClientId: '428557007573-49riei18ab978u1phttf4le57c1p0l7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.hoodhiveFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnAorSA7HRDUmn5cgd84kOfCPr_sTiuHg',
    appId: '1:428557007573:web:567cd92993ed0577fec05c',
    messagingSenderId: '428557007573',
    projectId: 'hoodjunction-a7605',
    authDomain: 'hoodjunction-a7605.firebaseapp.com',
    storageBucket: 'hoodjunction-a7605.firebasestorage.app',
    measurementId: 'G-01YLJYMX1Z',
  );
}
